package com.companion.ai.growth;
import com.companion.ai.LlmClient; import com.companion.ai.model.LlmResponse; import com.companion.ai.prompt.*; import com.companion.entity.CharacterGrowth; import com.fasterxml.jackson.databind.ObjectMapper; import org.junit.jupiter.api.Test; import org.springframework.core.io.DefaultResourceLoader;
import static org.assertj.core.api.Assertions.assertThat; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
class LlmGrowthEvaluatorTest {
 @Test void validAndUnchangedAreHandled(){LlmClient c=mock(LlmClient.class);respond(c,"{\"changed\":true,\"growthSummary\":\"calmer\",\"behaviorAdaptation\":\"concise\",\"userUnderstanding\":\"direct\",\"growthDirection\":\"continuity\"}");assertThat(evaluator(c).evaluate(new CharacterGrowth(),context()).changed()).isTrue();respond(c,"{\"changed\":false}");assertThat(evaluator(c).evaluate(new CharacterGrowth(),context()).changed()).isFalse();}
 @Test void identityRewriteAndWeakInteractionAreRejected(){LlmClient c=mock(LlmClient.class);respond(c,"{\"changed\":true,\"growthSummary\":\"replace personality\",\"behaviorAdaptation\":\"x\",\"userUnderstanding\":\"x\",\"growthDirection\":\"x\"}");assertThat(evaluator(c).evaluate(new CharacterGrowth(),context()).changed()).isFalse();assertThat(evaluator(c).evaluate(new CharacterGrowth(),new GrowthEvaluationContext("i","r","m","你好！","a")).changed()).isFalse();}
 @Test void malformedEmptyProviderMissingAndUnknownAreUnchanged(){LlmClient c=mock(LlmClient.class);LlmGrowthEvaluator e=evaluator(c);for(String json:new String[]{"not-json","","{\"changed\":true,\"growthSummary\":\"x\"}","{\"changed\":true,\"growthSummary\":\"x\",\"behaviorAdaptation\":\"x\",\"userUnderstanding\":\"x\",\"growthDirection\":\"x\",\"personality\":\"new\"}"}){respond(c,json);assertThat(e.evaluate(new CharacterGrowth(),context()).changed()).isFalse();reset(c);}when(c.complete(anyString(),anyString(),anyInt())).thenThrow(new RuntimeException("down"));assertThat(e.evaluate(new CharacterGrowth(),context()).changed()).isFalse();}
 @Test void overlongFieldIsUnchanged(){LlmClient c=mock(LlmClient.class);respond(c,"{\"changed\":true,\"growthSummary\":\""+"x".repeat(1001)+"\",\"behaviorAdaptation\":\"x\",\"userUnderstanding\":\"x\",\"growthDirection\":\"x\"}");assertThat(evaluator(c).evaluate(new CharacterGrowth(),context()).changed()).isFalse();}
 @Test void promptSeparatesAndBoundsAllContext(){LlmClient c=mock(LlmClient.class);respond(c,"{\"changed\":false}");evaluator(c).evaluate(new CharacterGrowth(),new GrowthEvaluationContext("IDENTITY-"+"i".repeat(5000),"REL","MEM","meaningful user","assistant"));var p=org.mockito.ArgumentCaptor.forClass(String.class);verify(c).complete(anyString(),p.capture(),anyInt());assertThat(p.getValue()).contains("Character Identity:","Current Growth:","Relationship:","Memory:","Recent Interaction:","USER:","ASSISTANT:","IDENTITY-").doesNotContain("i".repeat(4001));}
 private GrowthEvaluationContext context(){return new GrowthEvaluationContext("identity","relationship","memory","meaningful recurring preference","assistant");} private LlmGrowthEvaluator evaluator(LlmClient c){PromptTemplateRenderer r=new PromptTemplateRenderer();return new LlmGrowthEvaluator(c,new ObjectMapper(),new ClasspathPromptTemplateLoader(new DefaultResourceLoader(),r),r);} private void respond(LlmClient c,String json){when(c.complete(anyString(),anyString(),anyInt())).thenReturn(new LlmResponse(json,"m","m","stop",null,null));}
}
