<template>
  <section v-if="detail" class="step-detail" :data-kind="detail.kind" :data-tool="detail.toolName || undefined">
    <header class="detail-header"><div><span class="eyebrow">STEP {{ step.stepNumber }}</span><h2>{{ detail.presentation.label }}</h2></div><span class="phase">{{ detail.presentation.phase }}</span></header>
    <section v-if="detail.kind==='duplicate'" class="guard-note"><strong>Reused Previous Result</strong><p>The same completed tool call had already succeeded, so the Agent reused the existing result instead of executing it again.</p></section>
    <section v-if="detail.kind==='failed'" class="failure-note"><strong>Step Failed</strong><span>{{ detail.errorCode || 'STEP_ERROR' }}</span><p>{{ detail.errorMessage || 'The step could not be completed.' }}</p></section>
    <section class="detail-section"><h3>Decision Summary</h3><p>{{ detail.decisionSummary }}</p></section>
    <section v-if="detail.toolName" class="detail-section tool-section"><div class="section-heading"><h3>Tool</h3><span>Read-only</span></div><strong>{{ detail.tool.label }}</strong><code>{{ detail.toolName }}</code><p>{{ detail.tool.description }}</p></section>
    <AgentPayloadBlock v-if="detail.toolName" title="Arguments" :payload="detail.arguments" />
    <section v-if="detail.waitingForResult" class="waiting-result" role="status"><strong>Tool in progress</strong><p>Waiting for tool result.</p></section>
    <AgentPayloadBlock v-else-if="detail.kind==='tool'||detail.kind==='duplicate'||detail.kind==='final'" :title="detail.resultLabel" :payload="detail.result" />
    <section class="detail-section metadata"><h3>Execution Metadata</h3><dl><div><dt>Attempt</dt><dd>{{ detail.attemptSummary }}</dd></div><div><dt>Tool attempts</dt><dd>{{ detail.toolAttemptCount }}</dd></div><div><dt>Retries</dt><dd>{{ detail.retryCount }}</dd></div><div v-if="detail.toolCallId"><dt>Tool call ID</dt><dd class="technical">{{ detail.toolCallId }}</dd></div><div><dt>Created</dt><dd>{{ formatAgentTime(detail.createTime) }}</dd></div><div><dt>Updated</dt><dd>{{ formatAgentTime(detail.updateTime) }}</dd></div><div><dt>Completed</dt><dd>{{ formatAgentTime(detail.completionTime) }}</dd></div></dl></section>
  </section>
  <section v-else class="detail-empty"><div aria-hidden="true">◎</div><h2>选择执行步骤</h2><p>Select an execution step to inspect its details.</p></section>
</template>

<script setup>
import { computed } from 'vue'
import AgentPayloadBlock from './AgentPayloadBlock.vue'
import { buildAgentStepDetail, formatAgentTime } from '../../utils/agentPresentation'
const props=defineProps({step:{type:Object,default:null},runFinalResult:{type:String,default:''}})
const detail=computed(()=>buildAgentStepDetail(props.step,props.runFinalResult))
</script>

<style lang="scss" scoped>
.step-detail{min-width:0;display:grid;gap:14px}.detail-header,.section-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.eyebrow{color:var(--app-primary);font-size:10px;font-weight:850;letter-spacing:1.4px}.detail-header h2{margin-top:5px;font-size:21px}.phase,.section-heading span{padding:4px 8px;border-radius:var(--app-radius-pill);color:var(--app-primary-strong);font-size:10px;font-weight:800;background:var(--app-primary-soft)}.detail-section,.guard-note,.failure-note,.waiting-result{min-width:0;padding:14px;border:1px solid var(--app-border);border-radius:var(--app-radius-sm);background:var(--app-surface)}.detail-section h3{margin-bottom:8px;font-size:12px}.detail-section p,.guard-note p,.failure-note p,.waiting-result p{overflow-wrap:anywhere;line-height:1.55;color:var(--app-text-secondary);white-space:pre-wrap}.tool-section strong,.tool-section code{display:block}.tool-section code{overflow-wrap:anywhere;margin:5px 0 9px;color:var(--app-text-muted);font-size:10px}.guard-note{border-color:#bfe1d3;background:var(--app-success-soft)}.guard-note strong{color:var(--app-success)}.failure-note{border-color:#efcaca;background:var(--app-danger-soft)}.failure-note strong,.failure-note span{display:block;color:var(--app-danger)}.failure-note span{margin:5px 0;font-family:ui-monospace,monospace}.waiting-result{color:var(--app-primary-strong);background:var(--app-primary-soft)}.metadata dl{display:grid;gap:8px}.metadata dl div{min-width:0;display:grid;grid-template-columns:95px minmax(0,1fr);gap:8px}.metadata dt{color:var(--app-text-muted);font-size:11px}.metadata dd{min-width:0;overflow-wrap:anywhere}.technical{font:10px/1.45 ui-monospace,monospace;color:var(--app-text-secondary)}.detail-empty{min-height:420px;display:grid;place-content:center;justify-items:center;gap:9px;text-align:center}.detail-empty div{width:54px;height:54px;display:grid;place-items:center;border-radius:50%;color:var(--app-primary-strong);font-size:24px;background:var(--app-primary-soft)}.detail-empty p{color:var(--app-text-secondary)}
.step-detail{--detail-aura:rgba(184,165,255,.18);position:relative}.step-detail::before{content:'';position:absolute;z-index:-1;top:-18px;right:-18px;width:150px;height:150px;border-radius:50%;pointer-events:none;background:radial-gradient(circle,var(--detail-aura),transparent 70%)}.step-detail[data-tool="get_character_context"]{--detail-aura:rgba(170,138,255,.19)}.step-detail[data-tool="search_character_memory"]{--detail-aura:rgba(235,139,187,.16)}.step-detail[data-tool="get_world_context"]{--detail-aura:rgba(91,211,218,.17)}.detail-section,.guard-note,.failure-note,.waiting-result{border-color:rgba(225,222,255,.13);background:rgba(18,22,39,.82);box-shadow:inset 0 1px 0 rgba(255,255,255,.045)}.tool-section{position:relative;overflow:hidden}.tool-section::after{content:'';position:absolute;inset:0 auto 0 0;width:2px;background:var(--detail-aura)}.guard-note{position:relative;border-color:rgba(168,223,197,.24);background:linear-gradient(110deg,rgba(77,142,121,.14),rgba(28,36,48,.74))}.guard-note::after{content:'';position:absolute;right:14px;top:14px;width:18px;height:18px;border:3px double rgba(168,223,197,.55);border-radius:50%}.failure-note{border-color:rgba(240,170,169,.26);background:rgba(68,35,47,.62)}.phase,.section-heading span{border:1px solid rgba(225,222,255,.1);background:rgba(157,128,255,.12)}
/* Light diffuse-gradient overrides. */
.step-detail{--detail-aura:rgba(139,110,225,.15)}.step-detail[data-tool="get_character_context"]{--detail-aura:rgba(139,110,225,.16)}.step-detail[data-tool="search_character_memory"]{--detail-aura:rgba(235,109,164,.14)}.step-detail[data-tool="get_world_context"]{--detail-aura:rgba(63,193,204,.15)}.detail-section,.guard-note,.failure-note,.waiting-result{border-color:var(--agent-border,var(--app-border));background:rgba(255,255,253,.72);box-shadow:inset 0 1px 0 rgba(255,255,255,.82)}.guard-note{border-color:rgba(69,139,111,.2);background:linear-gradient(110deg,rgba(212,242,228,.7),rgba(255,255,253,.7))}.failure-note{border-color:rgba(190,86,100,.22);background:rgba(255,237,239,.78)}.phase,.section-heading span{border-color:rgba(76,91,96,.08);background:rgba(145,115,226,.1)}
</style>
