package com.companion.ai.growth;
import com.companion.ai.LlmClient; import com.companion.ai.json.LlmJsonObjectExtractor; import com.companion.ai.model.LlmResponse; import com.companion.ai.prompt.*; import com.companion.entity.CharacterGrowth; import com.fasterxml.jackson.databind.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Component; import java.util.Map;
@Component @RequiredArgsConstructor public class LlmGrowthEvaluator { private final LlmClient client; private final ObjectMapper mapper; private final PromptTemplateLoader loader; private final PromptTemplateRenderer renderer; static final int MAX=1000;
 public GrowthEvaluation evaluate(CharacterGrowth g,GrowthEvaluationContext c){ if(c==null||weak(c.userMessage())||c.assistantResponse()==null||c.assistantResponse().isBlank()) return GrowthEvaluation.unchanged(); try { String s=renderer.render(loader.load(PromptTemplateKey.GROWTH_EVALUATION_SYSTEM),Map.of()); String u=renderer.render(loader.load(PromptTemplateKey.GROWTH_EVALUATION_USER),Map.of("characterIdentity",bounded(c.characterIdentity()),"currentGrowth",current(g),"relationship",bounded(c.relationship()),"memory",bounded(c.memory()),"userMessage",bounded(c.userMessage()),"assistantResponse",bounded(c.assistantResponse()))); LlmResponse r=client.complete(s,u,700); JsonNode n=mapper.readTree(LlmJsonObjectExtractor.extract(r==null?null:r.content())); if(!allowedShape(n)||!n.path("changed").asBoolean(false)) return GrowthEvaluation.unchanged(); String a=text(n,"growthSummary"),b=text(n,"behaviorAdaptation"),cc=text(n,"userUnderstanding"),d=text(n,"growthDirection"); if(!valid(a)||!valid(b)||!valid(cc)||!valid(d)||contradictsIdentity(a,b,cc,d)) return GrowthEvaluation.unchanged(); return new GrowthEvaluation(true,a,b,cc,d); } catch(Exception e){return GrowthEvaluation.unchanged();} }
 private boolean allowedShape(JsonNode n){java.util.Set<String> allowed=java.util.Set.of("changed","growthSummary","behaviorAdaptation","userUnderstanding","growthDirection");java.util.Iterator<String> names=n.fieldNames();while(names.hasNext())if(!allowed.contains(names.next()))return false;return n.path("changed").isBoolean();}
 private boolean weak(String value){if(value==null||value.isBlank())return true;String x=value.trim().toLowerCase();return java.util.Set.of("hi","hello","hey","你好","您好","嗨","在吗","早上好","晚上好").contains(x.replaceAll("[\\p{Punct}。！？、，]+",""));}
 private String current(CharacterGrowth g){if(g==null)return "";return "growthSummary: "+safe(g.getGrowthSummary())+"\nbehaviorAdaptation: "+safe(g.getBehaviorAdaptation())+"\nuserUnderstanding: "+safe(g.getUserUnderstanding())+"\ngrowthDirection: "+safe(g.getGrowthDirection());}
 private String bounded(String s){s=safe(s);return s.substring(0,Math.min(s.length(),4000));}
 private boolean contradictsIdentity(String... values){ for(String value: values){ String x=value.toLowerCase(); if(x.contains("override identity")||x.contains("replace personality")||x.contains("rewrite background")||x.contains("change core goal")||x.contains("contradict speaking style")||x.contains("invent history")||x.contains("invent relationship")) return true; } return false; }
 private String text(JsonNode n,String k){return n.path(k).isTextual()?n.path(k).asText().trim():"";} private boolean valid(String s){return !s.isBlank()&&s.length()<=MAX;} private String safe(String s){return s==null?"":s;}
}
