package com.companion.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.companion.ai.worldmemory.*;import com.companion.dto.response.WorldResponse;import com.companion.entity.*;import com.companion.entity.enums.WorldRoundStatus;import com.companion.mapper.*;import com.companion.service.*;import lombok.RequiredArgsConstructor;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.LocalDateTime;import java.util.*;import java.util.stream.Collectors;
@Service @RequiredArgsConstructor public class WorldMemoryServiceImpl implements WorldMemoryService{
 static final int MAX_MEMORIES=10,MAX_CHARS=6000,MAX_ATTEMPTS=2;private final WorldMemoryMapper memories;private final CharacterWorldService worlds;private final WorldRoundMapper rounds;private final WorldEventMapper events;private final WorldParticipantMapper participants;private final LlmWorldMemoryExtractor extractor;
 public String getRelevantMemory(Long u,Long w,String q){worlds.get(u,w);String terms=q==null?"":q.toLowerCase();StringBuilder out=new StringBuilder();memories.selectList(new QueryWrapper<WorldMemory>().eq("user_id",u).eq("world_id",w)).stream().sorted(Comparator.<WorldMemory>comparingInt(m->score(m,terms)).reversed().thenComparing(WorldMemory::getUpdateTime,Comparator.nullsLast(Comparator.reverseOrder())).thenComparing(WorldMemory::getId,Comparator.nullsLast(Comparator.reverseOrder()))).limit(MAX_MEMORIES).map(m->"["+m.getMemoryType()+"] "+m.getContent()).forEach(s->{if(out.length()+s.length()+1<=MAX_CHARS)out.append(s).append('\n');});return out.toString();}
 public void extractAndStore(Long u,Long w,Long r){WorldResponse current=worlds.get(u,w);WorldRound round=rounds.selectOne(new QueryWrapper<WorldRound>().eq("id",r).eq("world_id",w));if(round==null||!WorldRoundStatus.COMPLETED.name().equals(round.getStatus()))return;String world=round.getWorldSnapshot()!=null?round.getWorldSnapshot():"LEGACY_FALLBACK:"+current.getName()+"\n"+current.getBackground()+"\n"+current.getRules()+"\n"+current.getAtmosphere()+"\n"+current.getScene();String transcript=events.selectList(new QueryWrapper<WorldEvent>().eq("round_id",r).orderByAsc("sequence_no").orderByAsc("id")).stream().map(e->e.getEventType()+": "+e.getContent()).collect(Collectors.joining("\n"));String roster=participants.selectList(new QueryWrapper<WorldParticipant>().eq("world_id",w).orderByAsc("display_order")).stream().map(WorldParticipant::getCharacterSnapshot).filter(Objects::nonNull).collect(Collectors.joining("\n"));for(WorldMemoryCandidate c:extractor.extract(new WorldMemoryExtractionContext(world,roster,transcript,getRelevantMemory(u,w,round.getUserInput()))))consolidate(u,w,r,c);}
 void consolidate(Long u,Long w,Long r,WorldMemoryCandidate c){String hash=hash(c.type().name()+"\n"+normalize(c.content()));WorldMemory exact=findHash(u,w,c.type().name(),hash);if(exact!=null)return;for(int attempt=0;attempt<MAX_ATTEMPTS;attempt++){WorldMemory keyed=c.key()==null?null:findKey(u,w,c.type().name(),c.key());if(keyed!=null){int v=keyed.getVersion()==null?0:keyed.getVersion();keyed.setContent(c.content());keyed.setDedupeHash(hash);keyed.setImportance(c.importance());keyed.setSourceRoundId(r);keyed.setUpdateTime(LocalDateTime.now());try{if(memories.updateIfVersionMatches(keyed,v)==1)return;}catch(DuplicateKeyException duplicate){if(findHash(u,w,c.type().name(),hash)!=null)return;}continue;}WorldMemory n=new WorldMemory();n.setUserId(u);n.setWorldId(w);n.setMemoryType(c.type().name());n.setMemoryKey(c.key());n.setContent(c.content());n.setDedupeHash(hash);n.setSourceRoundId(r);n.setImportance(c.importance());n.setVersion(0);n.setDeleted(0);n.setCreateTime(LocalDateTime.now());n.setUpdateTime(n.getCreateTime());try{memories.insert(n);return;}catch(DuplicateKeyException duplicate){if(findHash(u,w,c.type().name(),hash)!=null)return;}}}
 private WorldMemory findHash(Long u,Long w,String t,String h){return memories.selectOne(new QueryWrapper<WorldMemory>().eq("user_id",u).eq("world_id",w).eq("memory_type",t).eq("dedupe_hash",h));}private WorldMemory findKey(Long u,Long w,String t,String k){return memories.selectOne(new QueryWrapper<WorldMemory>().eq("user_id",u).eq("world_id",w).eq("memory_type",t).eq("memory_key",k).last("LIMIT 1"));}private String normalize(String s){return s.trim().replaceAll("\\s+"," ").toLowerCase(Locale.ROOT);}private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private int score(WorldMemory m,String q){int s=m.getImportance()==null?50:m.getImportance();for(String t:q.split("\\s+"))if(t.length()>1&&m.getContent().toLowerCase().contains(t))s+=20;return s;}
}
