CREATE TABLE t_character (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    character_type TINYINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    age SMALLINT DEFAULT NULL,
    identity VARCHAR(200) DEFAULT NULL,
    core_personality VARCHAR(1000) DEFAULT NULL,
    current_goal VARCHAR(500) DEFAULT NULL,
    biography TEXT DEFAULT NULL,
    relationship_to_user VARCHAR(300) DEFAULT NULL,
    speaking_style VARCHAR(500) DEFAULT NULL,
    profile_config JSON DEFAULT NULL,
    source_description VARCHAR(2000) DEFAULT NULL,
    generate_type TINYINT NOT NULL DEFAULT 0,
    visual_type TINYINT NOT NULL DEFAULT 0,
    avatar_id BIGINT DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    avatar_color VARCHAR(32) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    deleted TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_character_user_active_created (user_id, status, deleted, create_time),
    KEY idx_character_avatar_id (avatar_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
