ALTER TABLE t_world
    ADD COLUMN atmosphere VARCHAR(500) DEFAULT NULL;

ALTER TABLE t_world
    ADD COLUMN scene VARCHAR(1000) DEFAULT NULL;

ALTER TABLE t_world
    ADD COLUMN source_description VARCHAR(2000) DEFAULT NULL;
