package com.companion.agent.tool;
import com.companion.agent.AgentExecutionException;import com.companion.config.AgentProperties;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import java.time.Duration;import java.util.List;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;import static org.assertj.core.api.Assertions.*;
class AgentToolExecutorTest {ExecutorService pool;AgentProperties p;ObjectMapper json=new ObjectMapper();@BeforeEach void setup(){pool=Executors.newFixedThreadPool(2);p=new AgentProperties();p.setToolTimeout(Duration.ofMillis(40));}@AfterEach void close(){pool.shutdownNow();}
 @Test void oneExecuteCallPerformsExactlyOneSuccessfulAttempt(){AtomicInteger calls=new AtomicInteger();AgentTool t=tool(a->{calls.incrementAndGet();return "ok";});assertThat(executor(t).execute(1L,"test",json.createObjectNode())).isEqualTo("ok");assertThat(calls).hasValue(1);}
 @Test void transientFailureIsReturnedWithoutInternalRetry(){AtomicInteger calls=new AtomicInteger();AgentTool t=tool(a->{calls.incrementAndGet();throw new AgentExecutionException("TRANSIENT","retry",true);});assertThatThrownBy(()->executor(t).execute(1L,"test",json.createObjectNode())).isInstanceOfSatisfying(AgentExecutionException.class,e->assertThat(e.isRetryable()).isTrue());assertThat(calls).hasValue(1);}
 @Test void timeoutCancelsOneAttemptWithoutInternalRetry(){AtomicInteger calls=new AtomicInteger();AgentTool t=tool(a->{calls.incrementAndGet();try{Thread.sleep(500);}catch(InterruptedException e){Thread.currentThread().interrupt();}return "late";});assertThatThrownBy(()->executor(t).execute(1L,"test",json.createObjectNode())).isInstanceOfSatisfying(AgentExecutionException.class,e->assertThat(e.getCode()).isEqualTo("TOOL_TIMEOUT"));assertThat(calls).hasValue(1);}
 @Test void deterministicFailureIsReturnedWithoutRetry(){AtomicInteger calls=new AtomicInteger();AgentTool t=tool(a->{calls.incrementAndGet();throw new AgentExecutionException("DENIED","no",false);});assertThatThrownBy(()->executor(t).execute(1L,"test",json.createObjectNode())).isInstanceOfSatisfying(AgentExecutionException.class,e->assertThat(e.getCode()).isEqualTo("DENIED"));assertThat(calls).hasValue(1);}
 AgentToolExecutor executor(AgentTool t){return new AgentToolExecutor(new AgentToolRegistry(List.of(t)),pool,p);}interface F{String run(JsonNode n);}AgentTool tool(F f){return new AgentTool(){public String name(){return "test";}public String description(){return "";}public String inputSchema(){return "{}";}public void validate(JsonNode n){}public String execute(Long u,JsonNode n){return f.run(n);}};}
}
