package com.companion.growth;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper; import com.companion.ai.growth.*; import com.companion.common.exception.BusinessException; import com.companion.entity.*; import com.companion.entity.enums.CharacterType; import com.companion.mapper.*; import com.companion.service.CharacterGrowthService; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.test.context.ActiveProfiles; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@SpringBootTest @ActiveProfiles("soft-delete-test") @Transactional class CharacterGrowthIntegrationTest { @Autowired CharacterGrowthService service; @Autowired CharacterGrowthMapper growths; @Autowired CharacterMapper characters; @MockBean LlmGrowthEvaluator evaluator; Long a,b;
 @BeforeEach void setup(){a=character(801L,CharacterType.AI,1);b=character(801L,CharacterType.AI,1);when(evaluator.evaluate(any(),any())).thenReturn(GrowthEvaluation.unchanged());}
 @Test void createIsUniqueIsolatedAndDefaultsValid(){var one=service.getOrCreate(801L,a);var same=service.getOrCreate(801L,a);var other=service.getOrCreate(801L,b);assertThat(same.getId()).isEqualTo(one.getId());assertThat(other.getId()).isNotEqualTo(one.getId());assertThat(one.getGrowthSummary()).isNotBlank();assertThat(growths.selectCount(new QueryWrapper<CharacterGrowth>().eq("user_id",801L))).isEqualTo(2);}
 @Test void updateOnlyAAndUnchangedDoesNotWrite(){var one=service.getOrCreate(801L,a);var other=service.getOrCreate(801L,b);service.evaluateAndUpdate(801L,a,ctx());assertThat(growths.selectById(one.getId()).getVersion()).isZero();when(evaluator.evaluate(any(),any())).thenReturn(new GrowthEvaluation(true,"grown","adapt","understand","direction"));service.evaluateAndUpdate(801L,a,ctx());assertThat(growths.selectById(one.getId()).getGrowthSummary()).isEqualTo("grown");assertThat(growths.selectById(other.getId()).getGrowthSummary()).isNotEqualTo("grown");}
 @Test void ownershipTypeInactiveAndDeletedAreRejected(){Long user=character(801L,CharacterType.USER,1),other=character(802L,CharacterType.AI,1),inactive=character(801L,CharacterType.AI,0),deleted=character(801L,CharacterType.AI,1);characters.deleteById(deleted);assertThatThrownBy(()->service.getOrCreate(801L,user)).isInstanceOf(BusinessException.class);assertThatThrownBy(()->service.getOrCreate(801L,other)).isInstanceOf(BusinessException.class);assertThatThrownBy(()->service.getOrCreate(801L,inactive)).isInstanceOf(BusinessException.class);assertThatThrownBy(()->service.getOrCreate(801L,deleted)).isInstanceOf(BusinessException.class);}
 private GrowthEvaluationContext ctx(){return new GrowthEvaluationContext("i","r","m","meaningful","reply");} private Long character(Long u,CharacterType t,int status){var x=new AiCharacter();x.setUserId(u);x.setCharacterType(t.getCode());x.setName("C");x.setGenerateType(0);x.setVisualType(0);x.setStatus(status);x.setDeleted(0);x.setCreateTime(LocalDateTime.now());x.setUpdateTime(LocalDateTime.now());characters.insert(x);return x.getId();}
}
