<template>
  <div class="agent-page">
    <header class="agent-heading">
      <div><span class="eyebrow">GOAL-DRIVEN WORKSPACE</span><h1>Agent Workspace</h1><p>查看 Agent 如何使用上下文与只读工具完成目标。</p></div>
      <div class="heading-actions">
        <el-button class="mobile-runs" @click="runsDrawerOpen=true">最近执行</el-button>
        <el-button class="new-goal" type="primary" @click="openComposer">＋ 新建目标</el-button>
      </div>
    </header>

    <main v-if="agentStore.listLoading && agentStore.runs.length===0" class="page-state" v-loading="true" aria-live="polite"><p>正在加载 Agent Runs…</p></main>
    <main v-else-if="agentStore.listError && agentStore.runs.length===0" class="page-state page-state--error" role="alert"><span class="state-mark">!</span><h2>无法加载 Agent Workspace</h2><p>{{ agentStore.listError }}</p><el-button @click="loadRuns">重试</el-button></main>
    <main v-else-if="agentStore.runs.length===0" class="page-state page-state--empty">
      <span class="state-mark" aria-hidden="true">✦</span><h2>{{ AGENT_EMPTY_STATE.title }}</h2><p>{{ AGENT_EMPTY_STATE.description }}</p><el-button type="primary" @click="openComposer">＋ 新建目标</el-button>
    </main>

    <main v-else class="workspace-grid">
      <aside class="runs-panel" aria-label="最近 Agent Runs"><AgentRunList :runs="agentStore.runs" :selected-run-id="agentStore.selectedRunId" :loading="agentStore.listLoading" :error="agentStore.listError" @select="chooseRun" @retry="loadRuns" /></aside>
      <section class="workspace-panel" aria-label="Run Workspace" :aria-busy="agentStore.detailLoading">
        <div v-if="agentStore.detailError" class="detail-error" role="alert"><h2>无法加载 Run</h2><p>{{ agentStore.detailError }}</p><el-button v-if="agentStore.selectedRunId" @click="retryDetail">重试</el-button></div>
        <div v-else-if="agentStore.detailLoading && !visibleRun" class="workspace-placeholder" v-loading="true"><p>正在加载 Run 详情…</p></div>
        <div v-else-if="visibleRun" class="run-overview">
          <div v-if="agentStore.pollingWarning" class="polling-warning" role="status"><span>连接暂时异常</span><p>{{ agentStore.pollingWarning }} 已保留最近一次成功状态。</p></div>
          <header class="run-header"><div><span class="eyebrow">RUN #{{ visibleRun.id }}</span><h2>{{ summarizeAgentGoal(visibleRun.goal,120) }}</h2></div><div class="run-state-actions"><span class="run-status" :data-tone="statusView.tone">{{ statusView.label }}</span><el-button v-if="resumeVisible" type="primary" :loading="agentStore.resumeLoading" :disabled="agentStore.resumeLoading" :aria-label="resumeLabel" @click="resumeSelectedRun">{{ resumeLabel }}</el-button></div></header>
          <section class="recovery-card" :data-tone="recoveryView.tone" role="status"><strong>{{ recoveryView.label }}</strong><p>{{ recoveryView.description }}</p></section>
          <section v-if="agentStore.resumeError" class="resume-error" role="alert"><strong>Resume request failed</strong><p>{{ agentStore.resumeError }}</p><el-button v-if="resumeVisible" :loading="agentStore.resumeLoading" @click="resumeSelectedRun">Retry Resume</el-button></section>
          <section class="goal-card"><span>目标</span><p>{{ visibleRun.goal }}</p></section>
          <dl class="run-facts"><div><dt>执行进度</dt><dd>{{ visibleRun.currentStep }} / {{ visibleRun.maxSteps }}</dd></div><div><dt>恢复状态</dt><dd>{{ agentRecoveryLabel(visibleRun.recoveryState) }}</dd></div><div><dt>创建时间</dt><dd>{{ formatAgentTime(visibleRun.createTime) }}</dd></div><div><dt>更新时间</dt><dd>{{ formatAgentTime(visibleRun.updateTime) }}</dd></div><div><dt>完成时间</dt><dd>{{ formatAgentTime(visibleRun.completionTime) }}</dd></div><div><dt>可恢复</dt><dd>{{ visibleRun.canResume ? '是' : '否' }}</dd></div></dl>
          <section v-if="visibleRun.status==='FAILED'" class="result-card result-card--error" aria-labelledby="run-failure-title"><span>FAILED</span><h3 id="run-failure-title">Agent Run Failed</h3><strong>{{ visibleRun.lastErrorCode || 'AGENT_ERROR' }}</strong><p>{{ visibleRun.lastErrorMessage || '执行未能完成。' }}</p><small>Updated {{ formatAgentTime(visibleRun.updateTime) }} · Completed {{ formatAgentTime(visibleRun.completionTime) }}</small><el-button v-if="failedStep" @click="viewFailedStep">View failed step</el-button></section>
          <section v-else-if="visibleRun.status==='COMPLETED'" class="result-card final-result" aria-labelledby="final-result-title"><span class="completed-badge">COMPLETED</span><h3 id="final-result-title">Final Result</h3><AgentPayloadBlock title="Final Result" :payload="finalPayload" /><small>Completed {{ formatAgentTime(visibleRun.completionTime) }}</small></section>
          <AgentStepTimeline :steps="visibleRun.steps" :selected-step-id="selectedStepId" @select="selectStep" />
          <el-button v-if="selectedStep" class="mobile-detail" @click="detailDrawerOpen=true">查看 Step Detail</el-button>
        </div>
        <div v-else class="workspace-placeholder"><span class="state-mark" aria-hidden="true">↖</span><h2>选择一个 Run</h2><p>从最近执行中选择一项，查看目标与当前状态。</p></div>
      </section>
      <aside class="detail-panel" aria-label="Step Detail"><AgentStepDetail :step="selectedStep" :run-final-result="visibleRun?.finalResult||''" /></aside>
    </main>

    <el-drawer v-model="runsDrawerOpen" class="agent-v2-drawer" title="最近执行" direction="ltr" size="min(88vw, 340px)"><AgentRunList :runs="agentStore.runs" :selected-run-id="agentStore.selectedRunId" :loading="agentStore.listLoading" :error="agentStore.listError" @select="chooseRun" @retry="loadRuns" /></el-drawer>
    <el-drawer v-model="detailDrawerOpen" class="agent-v2-drawer" title="Step Detail" direction="rtl" size="min(92vw, 420px)"><AgentStepDetail :step="selectedStep" :run-final-result="visibleRun?.finalResult||''" /></el-drawer>
    <el-dialog v-model="composerOpen" title="新建 Agent Goal" width="min(92vw, 620px)" :close-on-click-modal="!agentStore.createLoading" :close-on-press-escape="!agentStore.createLoading">
      <div class="goal-composer"><label for="agent-goal">Goal</label><el-input id="agent-goal" v-model="goalDraft" type="textarea" :rows="7" maxlength="4000" show-word-limit resize="vertical" placeholder="描述你希望 Agent 完成的目标" :disabled="agentStore.createLoading" @keydown.ctrl.enter.prevent="submitGoal" /><p class="composer-help">Agent 将根据目标自主选择可用的只读上下文工具。</p><div v-if="agentStore.createError" class="composer-error" role="alert"><strong>创建请求未确认</strong><p>{{ agentStore.createError }}</p><small>重试会复用同一个 requestId，避免创建重复 Run。</small></div></div>
      <template #footer><div class="composer-actions"><el-button :disabled="agentStore.createLoading" @click="composerOpen=false">取消</el-button><el-button v-if="agentStore.createError&&agentStore.pendingRequestId" type="primary" :loading="agentStore.createLoading" @click="retryGoal">重试同一请求</el-button><el-button v-else type="primary" :loading="agentStore.createLoading" :disabled="agentStore.createLoading" @click="submitGoal">创建 Run</el-button></div></template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router'
import AgentRunList from '../components/agent/AgentRunList.vue'
import AgentStepTimeline from '../components/agent/AgentStepTimeline.vue'
import AgentStepDetail from '../components/agent/AgentStepDetail.vue'
import AgentPayloadBlock from '../components/agent/AgentPayloadBlock.vue'
import { useAgentStore } from '../stores/agent'
import { AGENT_EMPTY_STATE, agentRecoveryLabel, agentStatusPresentation, canShowResume, chooseDefaultStep, finalResultPresentation, findFailedStep, formatAgentTime, getResumeLabel, getRunRecoveryPresentation, parseAgentRunId, shouldFollowLatestStep, summarizeAgentGoal } from '../utils/agentPresentation'

const route=useRoute(),router=useRouter(),agentStore=useAgentStore()
const runsDrawerOpen=ref(false),detailDrawerOpen=ref(false),composerOpen=ref(false),goalDraft=ref(''),selectedStepId=ref(null),followLatestStep=ref(true)
const visibleRun=computed(()=>agentStore.selectedRun?.id===agentStore.selectedRunId?agentStore.selectedRun:null)
const selectedStep=computed(()=>visibleRun.value?.steps.find(step=>step.id===selectedStepId.value)||null)
const statusView=computed(()=>agentStatusPresentation(visibleRun.value?.status))
const recoveryView=computed(()=>getRunRecoveryPresentation(visibleRun.value))
const resumeVisible=computed(()=>canShowResume(visibleRun.value))
const resumeLabel=computed(()=>getResumeLabel(visibleRun.value))
const failedStep=computed(()=>findFailedStep(visibleRun.value?.steps))
const finalPayload=computed(()=>finalResultPresentation(visibleRun.value?.finalResult))
const loadRuns=()=>agentStore.loadRuns().catch(()=>{})
const retryDetail=()=>agentStore.loadRun().catch(()=>{})
const chooseRun=async id=>{runsDrawerOpen.value=false;if(parseAgentRunId(route.query.runId)===id){await agentStore.selectRun(id).catch(()=>{});return}await router.replace({query:{...route.query,runId:String(id)}})}
const openComposer=()=>{agentStore.createError='';agentStore.pendingGoal='';agentStore.pendingRequestId='';goalDraft.value='';composerOpen.value=true}
const finishCreate=async run=>{if(!run)return;goalDraft.value='';composerOpen.value=false;await router.replace({query:{...route.query,runId:String(run.id)}})}
const submitGoal=async()=>{try{await finishCreate(await agentStore.createRun(goalDraft.value))}catch{}}
const retryGoal=async()=>{try{await finishCreate(await agentStore.retryCreate())}catch{}}
const selectStep=id=>{selectedStepId.value=id;followLatestStep.value=shouldFollowLatestStep(id,visibleRun.value?.steps||[]);if(typeof window!=='undefined'&&window.matchMedia?.('(max-width: 760px)').matches)detailDrawerOpen.value=true}
const resumeSelectedRun=async()=>{const id=visibleRun.value?.id;if(!id||id!==agentStore.selectedRunId||!canShowResume(visibleRun.value))return;await agentStore.resumeRun(id).catch(()=>{})}
const viewFailedStep=()=>{if(failedStep.value)selectStep(failedStep.value.id)}

watch(()=>agentStore.selectedRunId,()=>{selectedStepId.value=null;followLatestStep.value=true})
watch(()=>visibleRun.value?.steps||[],(steps,previousSteps)=>{
  if(steps.length===0){selectedStepId.value=null;followLatestStep.value=true;return}
  const stillExists=steps.some(step=>step.id===selectedStepId.value)
  const wasFollowing=followLatestStep.value||(!stillExists&&shouldFollowLatestStep(selectedStepId.value,previousSteps||[]))
  if(!stillExists||wasFollowing){selectedStepId.value=chooseDefaultStep(steps)?.id??null;followLatestStep.value=true}
})

const syncRouteRun=async value=>{
  if(value==null||value===''){if(agentStore.selectedRunId) await agentStore.selectRun(agentStore.selectedRunId).catch(()=>{});return}
  const id=parseAgentRunId(value)
  if(id&&agentStore.selectedRunId===id&&agentStore.selectedRun?.id===id){agentStore.startPolling(id);return}
  await agentStore.selectRun(value).catch(()=>{})
}
watch(()=>route.query.runId,syncRouteRun)
onMounted(async()=>{agentStore.attachVisibility();await loadRuns();await syncRouteRun(route.query.runId)})
onUnmounted(()=>agentStore.disposePolling())
onBeforeRouteLeave(()=>agentStore.disposePolling())
</script>

<style lang="scss" scoped>
.agent-page{min-width:0;min-height:calc(100dvh - 74px);padding:38px max(24px,calc((100% - 1440px)/2)) 52px;color:var(--app-text)}.agent-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:24px}.eyebrow{color:var(--app-primary);font-size:10px;font-weight:850;letter-spacing:1.6px}.agent-heading h1{margin:6px 0;font-size:38px;letter-spacing:-.035em}.agent-heading p,.workspace-placeholder p,.detail-placeholder p,.detail-placeholder small{color:var(--app-text-secondary)}.heading-actions{display:flex;gap:10px}.mobile-runs,.mobile-detail{display:none}
.workspace-grid{min-width:0;min-height:620px;display:grid;grid-template-columns:280px minmax(0,1fr) 340px;gap:18px}.runs-panel,.workspace-panel,.detail-panel{min-width:0}.workspace-panel,.detail-panel{border:1px solid var(--app-border);border-radius:var(--app-radius-lg);background:rgba(255,255,255,.9);box-shadow:var(--app-shadow-sm)}.workspace-panel{padding:28px}.detail-panel{padding:24px}
.run-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.run-header h2{max-width:700px;margin-top:7px;font-size:25px;line-height:1.28}.run-status{flex:0 0 auto;padding:7px 11px;border-radius:var(--app-radius-pill);font-weight:750;background:var(--app-surface-subtle)}.run-status[data-tone="running"]{color:var(--app-primary-strong);background:var(--app-primary-soft)}.run-status[data-tone="completed"]{color:var(--app-success);background:var(--app-success-soft)}.run-status[data-tone="failed"]{color:var(--app-danger);background:var(--app-danger-soft)}.run-status[data-tone="pending"]{color:var(--app-warning);background:var(--app-warning-soft)}
.goal-card,.result-card,.timeline-placeholder{margin-top:22px;padding:20px;border:1px solid var(--app-border);border-radius:var(--app-radius-md);background:var(--app-surface)}.goal-card span,.result-card span{display:block;margin-bottom:8px;color:var(--app-text-muted);font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:1px}.goal-card p,.result-card p{line-height:1.7;white-space:pre-wrap}.run-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:16px}.run-facts div{min-width:0;padding:14px;border-radius:var(--app-radius-sm);background:var(--app-surface-subtle)}.run-facts dt{margin-bottom:6px;color:var(--app-text-muted);font-size:11px}.run-facts dd{overflow:hidden;font-weight:700;text-overflow:ellipsis}.result-card--error{border-color:#efcaca;background:var(--app-danger-soft);color:var(--app-danger)}.result-card--error strong{display:block;margin-bottom:8px}.timeline-placeholder{display:flex;align-items:center;justify-content:space-between;gap:20px;border-style:dashed;background:var(--app-bg-cool)}.timeline-placeholder h3{margin-top:5px}.timeline-placeholder p{color:var(--app-text-muted)}
.polling-warning{margin-bottom:18px;padding:12px 14px;border:1px solid #efd49e;border-radius:var(--app-radius-sm);color:var(--app-warning);background:var(--app-warning-soft)}.polling-warning span{font-weight:800}.polling-warning p{margin-top:3px}.progress-list{margin-top:16px;padding:18px;border:1px solid var(--app-border);border-radius:var(--app-radius-md);background:var(--app-surface)}.progress-list>header{display:flex;justify-content:space-between}.progress-list>header p{color:var(--app-text-muted)}.progress-list ol{display:grid;gap:8px;margin-top:14px}.progress-list li{min-width:0;display:grid;grid-template-columns:28px minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px;border-radius:var(--app-radius-sm);background:var(--app-surface-subtle)}.progress-list li p{overflow:hidden;margin-top:2px;color:var(--app-text-secondary);text-overflow:ellipsis;white-space:nowrap}.progress-list li>span:last-child{color:var(--app-text-muted);font-size:10px;font-weight:750}.step-number{width:26px;height:26px;display:grid;place-items:center;border-radius:50%;color:var(--app-primary-strong);font-weight:800;background:var(--app-primary-soft)}
.workspace-placeholder,.detail-placeholder,.page-state{min-height:420px;display:grid;place-content:center;justify-items:center;gap:10px;text-align:center}.detail-placeholder{min-height:100%}.detail-symbol,.state-mark{width:54px;height:54px;display:grid;place-items:center;border-radius:50%;color:var(--app-primary-strong);font-size:24px;background:var(--app-primary-soft)}.detail-placeholder small{max-width:240px}.detail-error{padding:24px;border-radius:var(--app-radius-md);color:var(--app-danger);background:var(--app-danger-soft)}.detail-error p{margin:8px 0 14px}.page-state{width:min(720px,100%);min-height:460px;margin:30px auto;padding:40px;border:1px solid var(--app-border);border-radius:var(--app-radius-lg);background:rgba(255,255,255,.9);box-shadow:var(--app-shadow-lg)}.page-state p{max-width:520px;color:var(--app-text-secondary);line-height:1.6}.page-state--error .state-mark{color:var(--app-danger);background:var(--app-danger-soft)}
.goal-composer label{display:block;margin-bottom:8px;color:var(--app-text);font-weight:800}.composer-help{margin-top:9px;color:var(--app-text-secondary)}.composer-error{margin-top:16px;padding:14px;border-radius:var(--app-radius-sm);color:var(--app-danger);background:var(--app-danger-soft)}.composer-error p{margin:5px 0}.composer-actions{display:flex;justify-content:flex-end;gap:10px}.composer-actions :deep(.el-button)+.composer-actions :deep(.el-button){margin-left:0}
.run-state-actions{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:9px}.recovery-card,.resume-error{margin-top:16px;padding:16px 18px;border:1px solid var(--app-border);border-radius:var(--app-radius-md);background:var(--app-surface)}.recovery-card strong{display:block;margin-bottom:4px}.recovery-card p,.resume-error p{line-height:1.6;color:var(--app-text-secondary);white-space:pre-wrap}.recovery-card[data-tone="recoverable"]{border-color:#efd49e;background:var(--app-warning-soft)}.recovery-card[data-tone="running"]{border-color:#c9dff6;background:var(--app-primary-soft)}.resume-error{color:var(--app-danger);background:var(--app-danger-soft)}.resume-error p{margin:5px 0 10px}.final-result{display:grid;gap:10px}.final-result h3,.result-card--error h3{font-size:20px}.final-result small,.result-card--error small{color:var(--app-text-muted)}.completed-badge{width:max-content!important;margin:0!important;padding:4px 8px;border-radius:var(--app-radius-pill);color:var(--app-success)!important;background:var(--app-success-soft)}.result-card--error .el-button{width:max-content;margin-top:12px}
@media(max-width:1120px){.mobile-runs{display:inline-flex}.workspace-grid{grid-template-columns:minmax(0,1fr) 320px}.runs-panel{display:none}}
@media(max-width:760px){.agent-page{min-height:calc(100dvh - 112px);padding:28px 16px 40px}.agent-heading{align-items:flex-start;flex-direction:column}.agent-heading h1{font-size:31px}.heading-actions{width:100%;flex-wrap:wrap}.workspace-grid{min-height:520px;grid-template-columns:1fr}.workspace-panel{padding:20px}.detail-panel{display:none}.run-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.run-header,.timeline-placeholder{align-items:flex-start;flex-direction:column}.mobile-detail{display:inline-flex;margin-top:18px}.page-state{min-height:390px;margin:0}.agent-heading :deep(.el-button)+.agent-heading :deep(.el-button){margin-left:0}}
@media(max-width:430px){.run-facts{grid-template-columns:1fr}.heading-actions :deep(.el-button){flex:1 1 auto;margin-left:0}}

/* AIworld V2 prototype: scoped to the Agent workspace. Atmosphere stays soft; information stays sharp. */
.agent-page{--agent-bg:#111323;--agent-surface:rgba(24,28,48,.78);--agent-surface-strong:rgba(18,22,39,.94);--agent-surface-soft:rgba(42,47,72,.58);--agent-text:#f7f5ff;--agent-text-secondary:#cfcee0;--agent-text-muted:#9899b0;--agent-border:rgba(225,222,255,.16);--agent-border-strong:rgba(235,232,255,.28);--agent-glow-violet:rgba(149,117,255,.28);--agent-glow-cyan:rgba(90,220,225,.2);--agent-glow-rose:rgba(244,139,181,.18);--agent-glow-lime:rgba(199,224,142,.14);--agent-success:#a8dfc5;--agent-warning:#f1d5a5;--agent-danger:#f0aaa9;--agent-radius-sm:13px;--agent-radius-md:20px;--agent-radius-lg:28px;--agent-shadow:0 28px 70px rgba(3,5,18,.34),inset 0 1px 0 rgba(255,255,255,.08);--agent-blur:20px;--app-text:var(--agent-text);--app-text-secondary:var(--agent-text-secondary);--app-text-muted:var(--agent-text-muted);--app-border:var(--agent-border);--app-border-strong:var(--agent-border-strong);--app-surface:var(--agent-surface-strong);--app-surface-subtle:var(--agent-surface-soft);--app-bg-cool:rgba(17,20,36,.88);--app-primary:#b8a5ff;--app-primary-strong:#d8ceff;--app-primary-soft:rgba(157,128,255,.16);--app-success:var(--agent-success);--app-success-soft:rgba(104,190,151,.14);--app-warning:var(--agent-warning);--app-warning-soft:rgba(225,179,101,.14);--app-danger:var(--agent-danger);--app-danger-soft:rgba(218,102,109,.14);--app-radius-sm:var(--agent-radius-sm);--app-radius-md:var(--agent-radius-md);--app-radius-lg:var(--agent-radius-lg);position:relative;isolation:isolate;overflow:hidden;margin:-1px 0 0;background:var(--agent-bg)}
.agent-page::before{content:'';position:absolute;z-index:-2;inset:-18%;background:radial-gradient(circle at 16% 18%,var(--agent-glow-violet),transparent 30%),radial-gradient(circle at 84% 12%,var(--agent-glow-cyan),transparent 27%),radial-gradient(circle at 66% 74%,var(--agent-glow-rose),transparent 31%),radial-gradient(circle at 12% 86%,var(--agent-glow-lime),transparent 25%),radial-gradient(circle at 48% 46%,rgba(88,76,156,.15),transparent 36%);filter:saturate(.9);animation:agent-aura-drift 24s ease-in-out infinite alternate;transform-origin:center}
.agent-page::after{content:'';position:absolute;z-index:-1;inset:0;pointer-events:none;opacity:.055;background-image:repeating-radial-gradient(circle at 30% 20%,rgba(255,255,255,.8) 0 .55px,transparent .7px 3px);background-size:5px 5px;mix-blend-mode:soft-light}
.agent-heading,.workspace-grid,.page-state{position:relative;z-index:1}.agent-heading h1{font-weight:650;letter-spacing:-.045em;text-shadow:0 0 34px rgba(194,179,255,.2)}.agent-heading p{color:var(--agent-text-secondary)}.new-goal{box-shadow:0 8px 28px rgba(135,110,239,.22)}
.workspace-panel,.detail-panel,.page-state{border-color:var(--agent-border);background:linear-gradient(145deg,rgba(40,44,68,.72),rgba(19,23,41,.72));box-shadow:var(--agent-shadow);backdrop-filter:blur(var(--agent-blur)) saturate(1.08);-webkit-backdrop-filter:blur(var(--agent-blur)) saturate(1.08)}.workspace-panel{position:relative}.workspace-panel::before{content:'';position:absolute;inset:0 10% auto;height:1px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.3),transparent)}
.goal-card,.result-card,.recovery-card,.resume-error{border-color:var(--agent-border);background:var(--agent-surface-strong);box-shadow:inset 0 1px 0 rgba(255,255,255,.045)}.run-facts div{border:1px solid rgba(255,255,255,.055);background:rgba(30,34,55,.62)}.run-status{position:relative;padding-left:22px;border:1px solid var(--agent-border);background:rgba(25,29,47,.74)}.run-status::before{content:'';position:absolute;left:9px;top:50%;width:6px;height:6px;border-radius:50%;background:currentColor;box-shadow:0 0 12px currentColor;transform:translateY(-50%)}.run-status[data-tone="running"]{animation:agent-status-breathe 3.6s ease-in-out infinite}.polling-warning{border-color:rgba(241,213,165,.3);background:rgba(84,65,42,.48)}
.final-result{position:relative;overflow:hidden;border-color:rgba(184,165,255,.28)}.final-result::before{content:'';position:absolute;inset:0 0 auto;height:2px;background:linear-gradient(90deg,transparent,#c1aeff,#8fdae4,#edb4cc,transparent);opacity:.8}.result-card--error{border-color:rgba(240,170,169,.3);background:rgba(68,35,47,.66)}
:global(.agent-v2-drawer){--app-text:#f7f5ff;--app-text-secondary:#cfcee0;--app-text-muted:#9899b0;--app-border:rgba(225,222,255,.16);--app-surface:rgba(18,22,39,.94);--app-surface-subtle:rgba(42,47,72,.58);--app-primary:#b8a5ff;--app-primary-strong:#d8ceff;--app-primary-soft:rgba(157,128,255,.16);color:#f7f5ff!important;background:#171a2d!important}:global(.agent-v2-drawer .el-drawer__header){color:#f7f5ff}:global(.agent-v2-drawer .el-drawer__body){background:radial-gradient(circle at 100% 0,rgba(103,204,216,.12),transparent 34%),#171a2d}
@keyframes agent-aura-drift{from{transform:translate3d(-1%,0,0) scale(1)}to{transform:translate3d(1.5%,-1%,0) scale(1.025)}}@keyframes agent-status-breathe{50%{box-shadow:0 0 20px rgba(184,165,255,.12)}}
@media(max-width:760px){.agent-page{--agent-blur:12px}.agent-page::before{inset:-8%;background:radial-gradient(circle at 20% 10%,var(--agent-glow-violet),transparent 37%),radial-gradient(circle at 88% 66%,var(--agent-glow-cyan),transparent 38%)}.workspace-panel{backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}.run-state-actions{justify-content:flex-start}.run-header{align-items:flex-start;flex-direction:column}}
@media(prefers-reduced-motion:reduce){.agent-page::before,.run-status[data-tone="running"]{animation:none}.workspace-panel,.detail-panel,.run-item,.step-card{transition:none!important;scroll-behavior:auto!important}}
/* Diffuse-gradient redesign. Kept at the end so the functional A.2 styles remain intact. */
.agent-page{--agent-bg:#fbf8ef;--agent-surface:rgba(255,255,252,.72);--agent-surface-strong:rgba(255,255,253,.9);--agent-surface-soft:rgba(255,255,255,.58);--agent-text:#28333d;--agent-text-secondary:#59666e;--agent-text-muted:#7d898d;--agent-border:rgba(76,91,96,.13);--agent-border-strong:rgba(76,91,96,.2);--agent-glow-violet:rgba(157,130,255,.28);--agent-glow-cyan:rgba(70,208,221,.25);--agent-glow-rose:rgba(255,113,167,.24);--agent-glow-lime:rgba(180,226,96,.22);--agent-success:#397c68;--agent-warning:#9a6a24;--agent-danger:#b44d5c;--agent-shadow:0 24px 60px rgba(75,84,79,.11),inset 0 1px 0 rgba(255,255,255,.82);--agent-blur:28px;--app-text:var(--agent-text);--app-text-secondary:var(--agent-text-secondary);--app-text-muted:var(--agent-text-muted);--app-border:var(--agent-border);--app-border-strong:var(--agent-border-strong);--app-surface:var(--agent-surface-strong);--app-surface-subtle:var(--agent-surface-soft);--app-bg-cool:rgba(248,247,241,.72);--app-primary:#745ad5;--app-primary-strong:#5542a8;--app-primary-soft:rgba(131,102,224,.11);--app-success:var(--agent-success);--app-success-soft:rgba(85,164,134,.12);--app-warning:var(--agent-warning);--app-warning-soft:rgba(226,181,102,.16);--app-danger:var(--agent-danger);--app-danger-soft:rgba(218,102,121,.12);background:var(--agent-bg)}
.agent-page::before{inset:-16%;background:radial-gradient(ellipse at 7% 12%,var(--agent-glow-lime),transparent 28%),radial-gradient(ellipse at 33% 4%,var(--agent-glow-cyan),transparent 25%),radial-gradient(ellipse at 70% 9%,var(--agent-glow-rose),transparent 27%),radial-gradient(ellipse at 95% 24%,var(--agent-glow-violet),transparent 28%),radial-gradient(ellipse at 18% 74%,rgba(255,151,121,.2),transparent 29%),radial-gradient(ellipse at 63% 80%,rgba(95,204,232,.22),transparent 31%),radial-gradient(ellipse at 88% 88%,rgba(222,126,244,.18),transparent 25%);filter:blur(26px) saturate(1.08)}
.agent-page::after{opacity:.3;background:linear-gradient(115deg,rgba(255,255,255,.34),transparent 32%,rgba(255,255,255,.18) 68%,transparent);mix-blend-mode:normal}
.agent-heading h1{text-shadow:0 8px 28px rgba(107,89,167,.12)}.new-goal{border-color:transparent!important;background:linear-gradient(110deg,#6e69d9,#6aaecb)!important;box-shadow:0 10px 28px rgba(91,94,179,.2)}
.workspace-panel,.detail-panel,.page-state{border-color:var(--agent-border);background:linear-gradient(145deg,rgba(255,255,253,.84),rgba(250,249,245,.66));box-shadow:var(--agent-shadow);backdrop-filter:blur(var(--agent-blur)) saturate(1.08);-webkit-backdrop-filter:blur(var(--agent-blur)) saturate(1.08)}
.goal-card,.result-card,.recovery-card,.resume-error{border-color:var(--agent-border);background:var(--agent-surface-strong);box-shadow:inset 0 1px 0 rgba(255,255,255,.8)}.run-facts div{border-color:rgba(76,91,96,.08);background:rgba(255,255,255,.52)}.run-status{border-color:var(--agent-border);background:rgba(255,255,255,.68)}.polling-warning{border-color:rgba(180,132,55,.22);background:rgba(255,243,210,.72)}.result-card--error{border-color:rgba(190,86,100,.22);background:rgba(255,237,239,.78)}
:global(.agent-v2-drawer){--app-text:#28333d;--app-text-secondary:#59666e;--app-text-muted:#7d898d;--app-border:rgba(76,91,96,.13);--app-surface:rgba(255,255,253,.9);--app-surface-subtle:rgba(255,255,255,.58);--app-primary:#745ad5;--app-primary-strong:#5542a8;--app-primary-soft:rgba(131,102,224,.11);color:#28333d!important;background:#fbf8ef!important}:global(.agent-v2-drawer .el-drawer__header){color:#28333d}:global(.agent-v2-drawer .el-drawer__body){background:radial-gradient(circle at 100% 0,rgba(99,210,221,.2),transparent 34%),radial-gradient(circle at 0 70%,rgba(255,132,174,.16),transparent 32%),#fbf8ef}

/* Reference hierarchy: image five defines the diffuse field; the other images only lend light materials. */
.agent-page{--agent-bg:var(--app-page-background);--agent-border:var(--app-border);--agent-shadow:var(--app-shadow-floating),inset 0 1px 0 rgba(255,255,255,.72);--agent-glow-violet:var(--app-atmosphere-pale-violet);--agent-glow-cyan:var(--app-atmosphere-mist-blue);--agent-glow-rose:var(--app-atmosphere-soft-pink);--agent-glow-lime:var(--app-atmosphere-mint);background:linear-gradient(135deg,var(--app-page-background) 0%,#f4f4ec 46%,#f7eff2 100%)}
.agent-page::before{inset:-22%;opacity:.95;background:radial-gradient(ellipse 25% 22% at 8% 10%,rgba(163,240,82,.72),transparent 72%),radial-gradient(ellipse 27% 28% at 28% 5%,rgba(39,202,227,.58),transparent 72%),radial-gradient(ellipse 24% 26% at 56% 8%,rgba(255,92,163,.66),transparent 72%),radial-gradient(ellipse 26% 27% at 84% 12%,rgba(118,91,238,.63),transparent 72%),radial-gradient(ellipse 24% 30% at 100% 45%,rgba(255,159,69,.58),transparent 73%),radial-gradient(ellipse 29% 30% at 76% 92%,rgba(51,189,231,.54),transparent 74%),radial-gradient(ellipse 25% 28% at 43% 99%,rgba(247,102,177,.48),transparent 72%),radial-gradient(ellipse 25% 27% at 4% 78%,rgba(255,179,83,.52),transparent 72%);filter:blur(54px) saturate(1.22);transform:scale(1.08);animation:agent-aura-drift 20s ease-in-out infinite alternate}
.agent-page::after{opacity:.68;background:radial-gradient(circle at 15% 26%,rgba(255,255,255,.75) 0 1px,transparent 2px),radial-gradient(circle at 76% 18%,rgba(255,255,255,.72) 0 1.5px,transparent 2.5px),radial-gradient(circle at 88% 70%,rgba(255,255,255,.6) 0 1px,transparent 2px),linear-gradient(112deg,rgba(255,255,255,.48),transparent 30%,rgba(255,255,255,.16) 68%,transparent);background-size:170px 170px,240px 240px,210px 210px,auto;mix-blend-mode:soft-light}
.agent-heading{padding:10px 8px 2px}.agent-heading h1{font-size:42px;font-weight:680;color:#252d38}.agent-heading p{max-width:560px;color:#4c5962}.eyebrow{color:#6c55c4}
.workspace-grid{gap:14px}.workspace-panel,.detail-panel,.page-state{border-color:rgba(255,255,255,.48);background:linear-gradient(145deg,rgba(255,255,251,.54),rgba(255,255,255,.24));box-shadow:0 24px 64px rgba(70,70,91,.09),inset 0 1px 0 rgba(255,255,255,.8);backdrop-filter:blur(34px) saturate(1.18);-webkit-backdrop-filter:blur(34px) saturate(1.18)}
.workspace-panel{overflow:hidden}.workspace-panel::after{content:'';position:absolute;z-index:-1;inset:auto -10% -22% 22%;height:44%;border-radius:50%;background:radial-gradient(ellipse,rgba(69,207,218,.15),rgba(246,112,174,.09) 42%,transparent 72%);filter:blur(22px)}
.detail-panel{position:relative;overflow:hidden}.detail-panel::after{content:'';position:absolute;z-index:-1;right:-28%;top:8%;width:76%;height:38%;border-radius:50%;background:radial-gradient(ellipse,rgba(142,108,235,.17),rgba(255,119,169,.1) 46%,transparent 72%);filter:blur(24px)}
.goal-card,.result-card,.recovery-card,.resume-error,.run-facts div{background:rgba(255,255,255,.47);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}
.new-goal{background:linear-gradient(110deg,rgba(112,85,218,.92),rgba(64,183,210,.9),rgba(239,104,161,.82))!important;background-size:180% 100%!important}
@media(max-width:760px){.agent-heading{padding-inline:0}.agent-heading h1{font-size:32px}.agent-page::before{inset:-18%;opacity:.82;filter:blur(42px);background:radial-gradient(ellipse at 12% 8%,rgba(152,234,80,.6),transparent 32%),radial-gradient(ellipse at 82% 15%,rgba(255,89,164,.55),transparent 34%),radial-gradient(ellipse at 16% 68%,rgba(255,168,72,.42),transparent 36%),radial-gradient(ellipse at 86% 78%,rgba(61,195,224,.48),transparent 38%)}}
</style>
