<template>
  <div class="home-page">
    <main>
      <section class="welcome-card app-surface--glass" aria-labelledby="home-title">
        <div class="welcome-copy"><span class="eyebrow">YOUR STORY SPACE</span><h1 id="home-title">欢迎回来，{{ userStore.nickname || '创造者' }}</h1><p>和你的角色继续聊天，或带他们进入一个全新的世界。</p><div class="welcome-actions"><el-button type="primary" size="large" @click="router.push('/chat')">开始聊天</el-button><el-button size="large" @click="router.push('/worlds/create')">创建世界</el-button></div></div>
        <div class="avatar-stage" aria-label="当前用户身份"><span class="identity-orbit" aria-hidden="true"></span><SimpleAvatar :name="homeAvatar.name" :image-url="homeAvatar.imageUrl" :avatar-color="homeAvatar.avatarColor" :entity-key="homeAvatar.key" type="USER" status="online" :size="160" shape="rounded" /><strong>{{ homeAvatar.name }}</strong><span>{{ homeAvatar.caption }}</span><el-button v-if="!currentUserCharacter" link type="primary" @click="router.push('/character/create?type=USER')">创建用户身份</el-button></div>
      </section>
      <section class="quick-section">
        <div class="section-heading"><div><span class="eyebrow">QUICK START</span><h2>从这里开始</h2></div><span>选择一个空间，继续你的故事</span></div>
        <div class="quick-grid"><button v-for="item in quickActions" :key="item.path" type="button" class="quick-card app-surface" :aria-label="`${item.title}：${item.description}`" @click="router.push(item.path)"><span class="quick-icon" :class="item.accent" aria-hidden="true">{{ item.icon }}</span><span><strong>{{ item.title }}</strong><small>{{ item.description }}</small></span><b aria-hidden="true">→</b></button></div>
      </section>
      <section class="collection-card app-surface--elevated"><div><span class="eyebrow">MY CHARACTERS</span><h2>我的人物</h2><p>{{ collectionText }}</p></div><div class="avatar-row" :class="{ 'app-empty-state': !previewCharacters.length }" aria-label="已创建的人物"><SimpleAvatar v-for="item in previewCharacters" :key="`${item.kind}-${item.id}`" :name="item.name" :image-url="item.imageUrl" :avatar-color="item.avatarColor" :entity-key="`${item.kind}-${item.id}`" :type="item.type" size="sm" shape="circle" /><span v-if="!previewCharacters.length" class="empty-note">还没有人物，先创建一个吧</span></div><el-button @click="router.push('/characters')">管理角色</el-button></section>
    </main>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getCharacterList } from '../api/character'
import { useUserStore } from '../stores/user'
import SimpleAvatar from '../components/ui/SimpleAvatar.vue'
const router=useRouter(),userStore=useUserStore();const characters=ref([])
const quickActions=[{title:'创建角色',description:'用描述生成可编辑的人物设定',icon:'✦',accent:'mint',path:'/character/create'},{title:'角色空间',description:'查看和管理你创建的角色',icon:'☺',accent:'sky',path:'/characters'},{title:'我的世界',description:'创建世界并安排互动阵容',icon:'◎',accent:'peach',path:'/worlds'},{title:'普通聊天',description:'与当前 AI 伙伴单独对话',icon:'◇',accent:'lavender',path:'/chat'}]
const characterItems=computed(()=>characters.value.map(item=>({...item,kind:'character',type:item.characterType})))
const currentUserCharacter=computed(()=>userStore.userInfo.currentUserCharacter||null)
const previewCharacters=computed(()=>characterItems.value.filter(item=>item.characterType==='AI').slice(0,5))
const homeAvatar=computed(()=>{const selected=currentUserCharacter.value;if(selected)return{...selected,key:`user-character-${selected.id}`,caption:selected.identity||'当前用户身份'};return{key:`default-${userStore.userInfo.id||'user'}`,name:'尚未设置用户身份',imageUrl:'',avatarColor:'',caption:'创建并选择一个 USER Character'}})
const collectionText=computed(()=>previewCharacters.value.length?`你已经创建了 ${characterItems.value.filter(item=>item.characterType==='AI').length} 个 AI Character。`:'还没有 AI Character。')
onMounted(async()=>{const results=await Promise.allSettled([userStore.getUserInfoAction(),getCharacterList()]);if(results[1].status==='fulfilled')characters.value=results[1].value?.data||results[1].value||[]})
</script>

<style lang="scss" scoped>
.home-page{min-width:0;min-height:calc(100dvh - 74px);color:var(--app-text-primary)}
main{width:min(var(--app-content-width,1180px),calc(100% - 48px));min-width:0;margin:auto;padding:42px 0 64px}.welcome-card{position:relative;min-width:0;min-height:360px;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(250px,.65fr);align-items:center;gap:40px;padding:48px;overflow:hidden}.welcome-card::after{content:'';position:absolute;right:-8%;bottom:-30%;width:42%;height:72%;border-radius:50%;pointer-events:none;background:radial-gradient(ellipse,var(--app-atmosphere-soft-pink),transparent 68%);opacity:.45}.welcome-copy,.avatar-stage{position:relative;z-index:1;min-width:0}.eyebrow{color:var(--app-accent-primary-strong);font-size:var(--app-type-label);font-weight:850;letter-spacing:1.8px}.welcome-copy h1{max-width:680px;margin:10px 0 14px;overflow-wrap:anywhere;font-size:var(--app-type-display);line-height:1.08;letter-spacing:-.04em}.welcome-copy p,.section-heading>span,.collection-card p{color:var(--app-text-secondary);font-size:var(--app-type-body);line-height:1.7}.welcome-actions{display:flex;flex-wrap:wrap;gap:var(--app-control-gap);margin-top:28px}:deep(.el-button){min-height:44px;margin-left:0;border-radius:var(--app-radius-sm);font-weight:750}:deep(.el-button--primary){--el-button-bg-color:var(--app-accent-primary);--el-button-border-color:var(--app-accent-primary);--el-button-hover-bg-color:var(--app-accent-primary-strong);--el-button-hover-border-color:var(--app-accent-primary-strong)}
.avatar-stage{min-height:280px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px;border:1px solid rgba(116,90,213,.12);border-radius:44% 56% 52% 48%;background:linear-gradient(145deg,rgba(232,246,255,.84),rgba(232,251,243,.74));box-shadow:inset 0 1px 0 rgba(255,255,255,.88),var(--app-shadow-card)}.identity-orbit{position:absolute;inset:11%;margin:0!important;border:1px solid rgba(116,90,213,.15);border-radius:50%;transform:rotate(-12deg)}.avatar-stage::before,.avatar-stage::after{content:'';position:absolute;border-radius:50%}.avatar-stage::before{width:48px;height:48px;right:8%;top:6%;background:var(--app-peach-soft)}.avatar-stage::after{width:28px;height:28px;left:10%;bottom:13%;background:var(--app-lavender-soft)}.avatar-stage strong{max-width:100%;margin-top:18px;overflow-wrap:anywhere;text-align:center;font-size:20px}.avatar-stage>span:not(.identity-orbit){max-width:100%;margin-top:5px;color:var(--app-text-secondary);text-align:center;overflow-wrap:anywhere}
.quick-section{margin-top:var(--app-section-gap)}.section-heading{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:17px}.section-heading h2,.collection-card h2{margin:5px 0 0;font-size:var(--app-type-section-title)}.quick-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px}.quick-card{min-width:0;min-height:150px;display:flex;align-items:flex-start;gap:14px;padding:var(--app-card-padding);text-align:left;transition:border-color var(--app-motion-normal) var(--app-ease-standard),box-shadow var(--app-motion-normal) var(--app-ease-standard),transform var(--app-motion-normal) var(--app-ease-standard)}.quick-card:hover{transform:translateY(-2px);border-color:var(--app-accent-secondary);box-shadow:var(--app-shadow-card)}.quick-card>span:nth-child(2){min-width:0;display:flex;flex:1;flex-direction:column}.quick-card strong,.quick-card small{overflow-wrap:anywhere}.quick-card strong{font-size:17px}.quick-card small{margin-top:8px;color:var(--app-text-secondary);line-height:1.5}.quick-card>b{color:var(--app-accent-primary);font-size:18px}.quick-icon{width:42px;height:42px;display:grid;place-items:center;flex:0 0 auto;border-radius:13px;font-size:21px}.quick-icon.mint{background:var(--app-mint-soft)}.quick-icon.sky{background:var(--app-sky-soft)}.quick-icon.peach{background:var(--app-peach-soft)}.quick-icon.lavender{background:var(--app-lavender-soft)}
.collection-card{min-width:0;margin-top:24px;display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:28px;padding:25px 28px}.avatar-row{min-width:0;display:flex;align-items:center}.avatar-row.app-empty-state{min-height:58px;padding:12px 16px}.avatar-row :deep(.simple-avatar){margin-left:-8px}.avatar-row :deep(.simple-avatar:first-child){margin-left:0}.empty-note{color:var(--app-text-muted);overflow-wrap:anywhere}
@media(max-width:1024px){main{width:calc(100% - 40px)}.welcome-card{grid-template-columns:minmax(0,1.15fr) minmax(240px,.85fr);gap:28px;padding:36px}.quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.collection-card{grid-template-columns:minmax(0,1fr) auto}.avatar-row{grid-column:1/-1;grid-row:2}}
@media(max-width:768px){.home-page{min-height:calc(100dvh - 112px)}main{width:calc(100% - 32px);padding:28px 0 44px}.welcome-card{grid-template-columns:1fr;padding:28px 22px}.avatar-stage{grid-row:1;min-height:235px}.section-heading{align-items:flex-start;flex-direction:column;gap:5px}.collection-card{grid-template-columns:1fr;padding:22px}.collection-card :deep(.el-button){justify-self:start}.avatar-row{grid-row:auto;max-width:100%;flex-wrap:wrap;gap:8px}.avatar-row :deep(.simple-avatar){margin-left:0}}
@media(max-width:480px){main{width:calc(100% - 24px)}.welcome-card{padding:24px 18px}.quick-grid{grid-template-columns:1fr}.welcome-actions :deep(.el-button){flex:1 1 130px}.avatar-stage{min-height:220px;padding:22px}.quick-card{min-height:132px}.collection-card{gap:18px}}
@media(prefers-reduced-motion:reduce){.quick-card{transition:none}.quick-card:hover{transform:none}}
@media(forced-colors:active){.welcome-card,.avatar-stage,.quick-card,.collection-card{border:1px solid CanvasText}}
</style>
