<template><div class="auth-page"><div class="orb orb-one"></div><div class="orb orb-two"></div><main class="auth-card"><div class="auth-mark"><el-icon :size="30"><MagicStick /></el-icon></div><span class="eyebrow">WELCOME BACK</span><h1>欢迎回来</h1><p>登录后继续你的角色与世界故事</p><el-form ref="formRef" :model="form" :rules="rules" @submit.prevent="handleLogin"><el-form-item prop="username"><el-input v-model="form.username" placeholder="请输入用户名" size="large" :prefix-icon="User" clearable /></el-form-item><el-form-item prop="password"><el-input v-model="form.password" :type="showPassword?'text':'password'" placeholder="请输入密码" size="large" :prefix-icon="Lock"><template #suffix><el-icon class="toggle-icon" role="button" aria-label="切换密码显示" @click="showPassword=!showPassword"><View v-if="!showPassword"/><Hide v-else/></el-icon></template></el-input></el-form-item><el-button native-type="submit" type="primary" size="large" class="submit-button" :loading="loading">{{ loading?'登录中…':'登录' }}</el-button></el-form><footer><span>还没有账号？</span><RouterLink to="/register">立即注册</RouterLink></footer></main></div></template>
<script setup>
import{reactive,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage}from'element-plus';import{Hide,Lock,MagicStick,User,View}from'@element-plus/icons-vue';import{useUserStore}from'../stores/user'
const router=useRouter(),route=useRoute(),userStore=useUserStore(),formRef=ref(null),loading=ref(false),showPassword=ref(false);const form=reactive({username:String(route.query.username||''),password:''});const rules={username:[{required:true,message:'请输入用户名',trigger:'blur'},{min:3,max:32,message:'用户名长度为 3-32 个字符',trigger:'blur'}],password:[{required:true,message:'请输入密码',trigger:'blur'},{min:6,max:32,message:'密码长度为 6-32 个字符',trigger:'blur'}]}
async function handleLogin(){if(!formRef.value||loading.value)return;const valid=await formRef.value.validate().catch(()=>false);if(!valid)return;loading.value=true;try{await userStore.login({username:form.username,password:form.password});ElMessage.success('登录成功');await router.push(route.query.redirect||'/home')}catch{}finally{loading.value=false}}
</script>
<style lang="scss" scoped>
.auth-page{position:relative;min-height:100vh;display:grid;place-items:center;padding:40px 20px;overflow:hidden;color:var(--app-text);background:radial-gradient(circle at 12% 12%,rgba(144,231,197,.42),transparent 30%),radial-gradient(circle at 90% 18%,rgba(131,205,243,.44),transparent 30%),radial-gradient(circle at 70% 92%,rgba(255,171,135,.3),transparent 27%),var(--app-bg)}.orb{position:absolute;border-radius:50%;filter:blur(1px);pointer-events:none}.orb-one{width:190px;height:190px;left:7%;bottom:10%;background:var(--app-lavender-soft)}.orb-two{width:110px;height:110px;right:11%;top:18%;background:var(--app-peach-soft)}.auth-card{position:relative;width:min(440px,100%);padding:42px 40px 32px;text-align:center;border:1px solid var(--app-border);border-radius:var(--app-radius-lg);background:rgba(255,255,255,.95);box-shadow:var(--app-shadow-lg)}.auth-mark{width:64px;height:64px;display:grid;place-items:center;margin:0 auto 18px;border-radius:20px;color:var(--app-primary-strong);background:linear-gradient(145deg,var(--app-sky-soft),var(--app-mint-soft))}.eyebrow{color:var(--app-primary-strong);font-size:11px;font-weight:850;letter-spacing:1.8px}h1{margin:7px 0 7px;font-size:32px;letter-spacing:-.03em}p{margin-bottom:27px;color:var(--app-text-secondary)}.el-form{text-align:left}:deep(.el-form-item){margin-bottom:18px}:deep(.el-input__wrapper){min-height:48px;border-radius:var(--app-radius-sm);background:var(--app-surface-subtle);box-shadow:0 0 0 1px var(--app-border-strong) inset}:deep(.el-input__wrapper.is-focus){box-shadow:0 0 0 1px var(--app-primary) inset,var(--app-focus-ring)}:deep(.el-input__inner){color:var(--app-text)}.toggle-icon{cursor:pointer;color:var(--app-text-muted)}.submit-button{width:100%;min-height:48px;margin-top:4px;border-radius:var(--app-radius-sm);font-weight:750;--el-button-bg-color:var(--app-primary);--el-button-border-color:var(--app-primary);--el-button-hover-bg-color:var(--app-primary-strong);--el-button-hover-border-color:var(--app-primary-strong)}footer{display:flex;justify-content:center;gap:7px;margin-top:24px;padding-top:20px;border-top:1px solid var(--app-border);color:var(--app-text-secondary)}footer a{color:var(--app-primary-strong);font-weight:750}@media(max-width:500px){.auth-card{padding:34px 22px 26px}}
</style>
